name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  release:
    types: [ created ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Log in to Quay.io
      env:
        QUAY_USERNAME: mazarineboelen+alm_workshop_auth
        QUAY_PASSWORD: 6IEBA5DNTSG80BYFLB5V1O0G2LZN6F02GOBMZ4BBHDXSQ8K5BT74DXCDQ4UV98MI
      run: |
        echo $QUAY_PASSWORD | docker login quay.io -u $QUAY_USERNAME --password-stdin
    - name: Extract release version
      if: github.event_name == 'release'
      run: echo "RELEASE_VERSION=${GITHUB_REF_NAME#v}" >> $GITHUB_ENV
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag quay.io/mazarineboelen/alm-workshop:$TAG
    - name: Tag Docker image
      run: docker tag quay.io/mazarineboelen/alm-workshop:latest quay.io/mazarineboelen/alm-workshop:$TAG
    - name: Push Docker image
      run: docker push quay.io/mazarineboelen/alm-workshop:latest
